### ISSUE TITLE
Problems in m-9

### ISSUE THREAD

**Issue by 0xErenes** [gothinkster/angular-realworld-example-app#144]
I've just bought a subscription in https://thinkster.io just to get a better understanding in this angular realworld example, and was unable to do a 'ng serve' in the very first task.

After some time I managed to make it work, here are some inconsistencies:

The page shoud recommend installing dependencies using 'yarn install' instead 'npm install' in https://thinkster.io/tutorials/building-real-world-angular-2-apps/page-layout-and-routing

'angular-cli.json' from m-9 branch should be replaced with 'angular.json' from master branch
'package.json' from m-9 should be replaced with 'package.json' from master
'tsconfig.json' and 'src/tsconfig.app.json' from master should be added in m-9
In src/app/shared/shared.module.ts it should be 
'import { HttpClientModule } from '@angular/common/http';' and not 
'import { HttpModule } from '@angular/http';'

After doing these changes the 'ng serve' run normally, but I'm very disappointed, since the page in https://thinkster.io/tutorials/building-real-world-angular-2-apps says this tutorial is up to date, even when there is a similar open problem in 'Issues' who never got a answer.

**Comment by dexmox** [comment]
I bought into this < 5 days ago - hit the same problem. 
Kind of disappointing.

**Comment by samisnotinsane** [comment]
After executing `yarn install` I get a build failure with the following:
`error C:\Data\angular-sites\angular-realworld-example-app\node_modules\node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments:
Directory: C:\Data\angular-sites\angular-realworld-example-app\node_modules\node-sass
`
In particular, it seems to be dependent on python2 which pops up later on in the stacktrace:
`gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
`
Overall not worth paying for the tutorials or following along with free version because as a newcomer to Angular, this project doesn't make it easy to only focus on the Angular code and instead I'm left to debug their old code.

**Comment by noakesey** [comment]
> I've just bought a subscription in https://thinkster.io just to get a better understanding in this angular realworld example, and was unable to do a 'ng serve' in the very first task.

Thanks matluz!  I'm in the same boat.  How much will a subscription to matluzster.io cost me? :-)
