### ISSUE TITLE
Doesn't follow Angular Style Guide regarding "Core" feature module

### ISSUE THREAD

**Issue by shaungrady** [gothinkster/angular-realworld-example-app#42]
https://angular.io/guide/styleguide#core-feature-module

The Angular Style Guide advises putting singleton services and single-use classes into the Core module. This app has everything in the Shared module.

**Comment by cfilby** [comment]
To add onto this, the SharedModule shouldn't be re-exporting the HttpModule since it's a provider only module. It seems like this should just be imported in the AppModule (or possibly the core module)?

The NgModule FAQ mentions this here:
https://angular.io/guide/ngmodule-faq#what-should-i-not-export
